# Generated by Django 5.2 on 2025-04-18 11:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_parentprofile_id_student_enrollment_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name', 'grade']},
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who enrolled the student.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('G7', 'Grade 7 (Form 1)'), ('G8', 'Grade 8 (Form 2)'), ('G9', 'Grade 9 (Form 3)'), ('G10', 'Grade 10 (Form 4)'), ('G11', 'Grade 11'), ('G12', 'Grade 12')], help_text="Select the student's current grade level (CBC System).", max_length=20),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
